/**
 * Radio Calico - Application Constants
 * Centralized configuration for project name, URLs, and other constants
 */

export const PROJECT_CONFIG = {
  NEXT_PUBLIC_PROJECT_NAME: process.env.NEXT_PUBLIC_PROJECT_NAME || 'project',
  NEXT_PUBLIC_PROJECT_URL: process.env.NEXT_PUBLIC_PROJECT_URL || 'http://localhost:3000',
  NEXT_PUBLIC_USER_EMAIL_CHANGE_TEMP_DISABLE_DURATION: process.env.NEXT_PUBLIC_USER_EMAIL_CHANGE_TEMP_DISABLE_DURATION || 3600000,
  NEXT_PUBLIC_RADIO_STREAM_URL: process.env.NEXT_PUBLIC_RADIO_STREAM_URL || "https://d3d4yli4hf5bmh.cloudfront.net/hls/live.m3u8",
  NEXT_PUBLIC_RADIO_METADATA_URL: process.env.NEXT_PUBLIC_RADIO_METADATA_URL || "https://d3d4yli4hf5bmh.cloudfront.net/metadatav2.json",
  NEXT_PUBLIC_RADIO_ALBUMART_URL: process.env.NEXT_PUBLIC_RADIO_ALBUMART_URL || "https://d3d4yli4hf5bmh.cloudfront.net/cover.jpg",
  NEXT_PUBLIC_METADATA_REFETCH_TIME: process.env.NEXT_PUBLIC_METADATA_REFETCH_TIME || 30000,
  NEXT_PUBLIC_TRACK_HISTORY_PAGINATION_LIMIT: process.env.NEXT_PUBLIC_TRACK_HISTORY_PAGINATION_LIMIT || 20
} as const

export const { 
  NEXT_PUBLIC_PROJECT_NAME, 
  NEXT_PUBLIC_PROJECT_URL, 
  NEXT_PUBLIC_USER_EMAIL_CHANGE_TEMP_DISABLE_DURATION, 
  NEXT_PUBLIC_RADIO_STREAM_URL, 
  NEXT_PUBLIC_RADIO_METADATA_URL, 
  NEXT_PUBLIC_RADIO_ALBUMART_URL, 
  NEXT_PUBLIC_METADATA_REFETCH_TIME, 
  NEXT_PUBLIC_TRACK_HISTORY_PAGINATION_LIMIT 
} = PROJECT_CONFIG

// Export for backward compatibility
export default PROJECT_CONFIG
